# Citizens CMD Plugin by Mateus Moreira
# @LichtHund
# Version ${project.version}
#
# Enables Checking for update.
check-updates: true
#
# Available languages EN, PT
lang: en
#
# The default npc cooldown in seconds
default-cooldown: 0
#
# When using a NPC with price, true means that to confirm the use the player needs to seek or press shift
shift-confirm: true
#
# Select cooldown display format, SHORT = 3m 3s | MEDIUM = 3 min 3 sec | FULL - 3 minutes 3 seconds
cooldonw-time-display: MEDIUM